export const STATION_REQUEST = 'STATION_REQUEST'
export const STATION_FAILURE = 'STATION_FAILURE'
export const STATION_SUCCESS = 'STATION_SUCCESS'

export const STATION_LIST_SUCCESS = 'STATION_LIST_SUCCESS'

export const STATION_SET_VIEW = 'STATION_SET_VIEW'
export const STATION_VIEW_ADD = 'STATION_VIEW_ADD'
export const STATION_VIEW_DISPENSER = 'STATION_VIEW_DISPENSER'
export const STATION_VIEW_EDIT = 'STATION_VIEW_EDIT'
export const STATION_VIEW_LIST = 'STATION_VIEW_LIST'
export const STATION_VIEW_PRODUCT = 'STATION_VIEW_PRODUCT'
export const STATION_VIEW_PRODUCT_SELECT = 'STATION_VIEW_PRODUCT_SELECT'
export const STATION_VIEW_PRODUCT_INVENTORY = 'STATION_VIEW_PRODUCT_INVENTORY'
